// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RegistroPedidos.DAL;

namespace RegistroPedidos.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20201024215905_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9");

            modelBuilder.Entity("RegistroPedidos.Entidades.Ordenes", b =>
                {
                    b.Property<int>("OrdenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Monto")
                        .HasColumnType("TEXT");

                    b.Property<int>("SuplidorId")
                        .HasColumnType("INTEGER");

                    b.HasKey("OrdenId");

                    b.HasIndex("SuplidorId");

                    b.ToTable("Ordenes");
                });

            modelBuilder.Entity("RegistroPedidos.Entidades.OrdenesDetalle", b =>
                {
                    b.Property<int>("OrdenDetalleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<float>("Cantidad")
                        .HasColumnType("REAL");

                    b.Property<decimal>("Costo")
                        .HasColumnType("TEXT");

                    b.Property<int>("OrdenId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("OrdenDetalleId");

                    b.HasIndex("OrdenId");

                    b.HasIndex("ProductoId");

                    b.ToTable("OrdenesDetalle");
                });

            modelBuilder.Entity("RegistroPedidos.Entidades.Productos", b =>
                {
                    b.Property<int>("ProductoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Costo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descripcion")
                        .HasColumnType("TEXT");

                    b.Property<float>("Inventario")
                        .HasColumnType("REAL");

                    b.HasKey("ProductoId");

                    b.ToTable("Productos");

                    b.HasData(
                        new
                        {
                            ProductoId = 1,
                            Costo = 75m,
                            Descripcion = "Jugo de naranja",
                            Inventario = 0f
                        },
                        new
                        {
                            ProductoId = 2,
                            Costo = 30m,
                            Descripcion = "Galletas saladas",
                            Inventario = 0f
                        },
                        new
                        {
                            ProductoId = 3,
                            Costo = 60m,
                            Descripcion = "Funda de pan sobao",
                            Inventario = 0f
                        },
                        new
                        {
                            ProductoId = 4,
                            Costo = 50m,
                            Descripcion = "Leche entera",
                            Inventario = 0f
                        },
                        new
                        {
                            ProductoId = 5,
                            Costo = 200m,
                            Descripcion = "Leche descremada",
                            Inventario = 0f
                        },
                        new
                        {
                            ProductoId = 6,
                            Costo = 10m,
                            Descripcion = "Hojuelitas de queso",
                            Inventario = 0f
                        },
                        new
                        {
                            ProductoId = 7,
                            Costo = 15m,
                            Descripcion = "Platanitos",
                            Inventario = 0f
                        },
                        new
                        {
                            ProductoId = 8,
                            Costo = 25m,
                            Descripcion = "Lays de queso",
                            Inventario = 0f
                        },
                        new
                        {
                            ProductoId = 9,
                            Costo = 50m,
                            Descripcion = "Lata de maíz",
                            Inventario = 0f
                        },
                        new
                        {
                            ProductoId = 10,
                            Costo = 35m,
                            Descripcion = "Lata de tomaticos",
                            Inventario = 0f
                        },
                        new
                        {
                            ProductoId = 11,
                            Costo = 60m,
                            Descripcion = "Botella de ketchup",
                            Inventario = 0f
                        });
                });

            modelBuilder.Entity("RegistroPedidos.Entidades.Suplidores", b =>
                {
                    b.Property<int>("SuplidorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombres")
                        .HasColumnType("TEXT");

                    b.HasKey("SuplidorId");

                    b.ToTable("Suplidores");

                    b.HasData(
                        new
                        {
                            SuplidorId = 1,
                            Nombres = "Rica"
                        },
                        new
                        {
                            SuplidorId = 2,
                            Nombres = "Guarina"
                        },
                        new
                        {
                            SuplidorId = 3,
                            Nombres = "Yoma"
                        },
                        new
                        {
                            SuplidorId = 4,
                            Nombres = "Frito Lays"
                        },
                        new
                        {
                            SuplidorId = 5,
                            Nombres = "La Famosa"
                        });
                });

            modelBuilder.Entity("RegistroPedidos.Entidades.Ordenes", b =>
                {
                    b.HasOne("RegistroPedidos.Entidades.Suplidores", null)
                        .WithMany("Ordenes")
                        .HasForeignKey("SuplidorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RegistroPedidos.Entidades.OrdenesDetalle", b =>
                {
                    b.HasOne("RegistroPedidos.Entidades.Ordenes", null)
                        .WithMany("Detalle")
                        .HasForeignKey("OrdenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RegistroPedidos.Entidades.Productos", null)
                        .WithMany("Detalle")
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
